services:
  bot_db:
    image: postgres:16-alpine3.18
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgres_tvgo:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  python_bot:
    build:
      context: ./mjtvbot
    ports:
      - "8082:8082"
    depends_on:
      bot_db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
      BOT_TOKEN: ${BOT_TOKEN}
      DP_NAME: ${POSTGRES_DB}
      DP_USER: ${POSTGRES_USER}
      DP_PASS: ${POSTGRES_PASSWORD}
      DP_HOST: ${POSTGRES_HOST}
      DP_PORT: ${POSTGRES_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - default

  go_tvgo:
    build:
      context: ./tvgo
      args:
        CI_JOB_LOGIN: ${CI_JOB_LOGIN}
        CI_JOB_TOKEN: ${CI_JOB_TOKEN}
    ports:
      - "8083:8083"
    depends_on:
      bot_db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - default

volumes:
  postgres_tvgo:

networks:
  default:
