name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check Docker Compose
        run: docker-compose version
      - name: Build and deploy
        run: |
          export CI_JOB_LOGIN=x
          export CI_JOB_TOKEN=${{ secrets.PAT_TOKEN }}
          export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          docker compose -f docker-compose.yml up --build --force-recreate --remove-orphans -d