name: CI Pipeline

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout кода
      - name: Checkout code
        uses: actions/checkout@v3

      # Настройка Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Сборка и запуск с помощью docker-compose
      - name: Build and start services
        run: |
          docker-compose up -d --build

      # Ожидание и проверка health checks
      - name: Test services
        run: |
          # Ожидание готовности базы данных
          until docker-compose exec -T bot_db pg_isready -U mirodil -d tvgo_db; do
            echo "Waiting for database..."
            sleep 5
          done
          # Проверка health endpoint для python_bot
          docker-compose exec -T python_bot curl -f http://localhost:8082/health || exit 1
          # Проверка health endpoint для go_tvgo
          docker-compose exec -T go_tvgo curl -f http://localhost:8083/health || exit 1

      # Остановка сервисов
      - name: Stop services
        run: |
          docker-compose down